package com.vaultflow.accounts.controller;

import com.fasterxml.jackson.databind.ObjectMapper;
import com.vaultflow.accounts.dto.AccountResponse;
import com.vaultflow.accounts.dto.CreateAccountRequest;
import com.vaultflow.accounts.dto.DepositRequest;
import com.vaultflow.accounts.dto.TransferRequest;
import com.vaultflow.accounts.dto.WithdrawRequest;
import com.vaultflow.accounts.entity.IdempotencyRecord;
import com.vaultflow.accounts.repository.IdempotencyRepository;
import com.vaultflow.accounts.service.AccountService;
import jakarta.validation.Valid;
import lombok.RequiredArgsConstructor;
import lombok.extern.slf4j.Slf4j;
import org.springframework.http.HttpStatus;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.*;

import java.util.List;
import java.util.Optional;
import java.util.UUID;

@Slf4j
@RestController
@RequestMapping("/api/accounts")
@RequiredArgsConstructor
public class AccountController {

    private final AccountService        accountService;
    private final IdempotencyRepository idempotencyRepository;
    private final ObjectMapper          objectMapper;

    @PostMapping
    @ResponseStatus(HttpStatus.CREATED)
    public AccountResponse createAccount(@RequestBody @Valid CreateAccountRequest request) {
        return accountService.createAccount(request);
    }

    @GetMapping("/{id}")
    public AccountResponse getAccount(@PathVariable UUID id) {
        return accountService.getAccount(id);
    }

    @GetMapping("/number/{accountNumber}")
    public AccountResponse getByAccountNumber(@PathVariable String accountNumber) {
        return accountService.getByAccountNumber(accountNumber);
    }

    @GetMapping
    public List<AccountResponse> getAllAccounts() {
        return accountService.getAllAccounts();
    }

    @PostMapping("/{id}/deposit")
    public AccountResponse deposit(@PathVariable UUID id,
                                   @RequestBody @Valid DepositRequest request) {
        return accountService.deposit(id, request);
    }

    @PostMapping("/{id}/withdraw")
    public AccountResponse withdraw(@PathVariable UUID id,
                                    @RequestBody @Valid WithdrawRequest request) {
        return accountService.withdraw(id, request);
    }

    /**
     * Transfer funds between accounts.
     *
     * Supports idempotency via the optional {@code Idempotency-Key} header.
     * If a key is supplied and a matching record already exists, the original
     * response is returned without re-processing — preventing double-spend on retries.
     *
     * The key should be a UUID generated by the client per logical operation.
     */
    @PostMapping("/{id}/transfer")
    public ResponseEntity<AccountResponse> transfer(
            @PathVariable UUID id,
            @RequestBody @Valid TransferRequest request,
            @RequestHeader(value = "Idempotency-Key", required = false) String idempotencyKey) {

        // ── Check for duplicate request ────────────────────────────────────────
        if (idempotencyKey != null && !idempotencyKey.isBlank()) {
            Optional<IdempotencyRecord> existing = idempotencyRepository.findById(idempotencyKey);
            if (existing.isPresent()) {
                IdempotencyRecord record = existing.get();
                log.info("Duplicate transfer request detected — returning cached result. key={}", idempotencyKey);
                try {
                    AccountResponse cached = objectMapper.readValue(record.getResponseBody(), AccountResponse.class);
                    return ResponseEntity.status(record.getStatus()).body(cached);
                } catch (Exception e) {
                    log.warn("Failed to deserialize cached idempotency response", e);
                    // Fall through and re-execute (safe degradation)
                }
            }
        }

        // ── Execute transfer ────────────────────────────────────────────────────
        AccountResponse result = accountService.transfer(id, request);

        // ── Persist idempotency record ──────────────────────────────────────────
        if (idempotencyKey != null && !idempotencyKey.isBlank()) {
            try {
                String body = objectMapper.writeValueAsString(result);
                idempotencyRepository.save(IdempotencyRecord.builder()
                        .idempotencyKey(idempotencyKey)
                        .accountId(id)
                        .status(HttpStatus.OK.value())
                        .responseBody(body)
                        .build());
            } catch (Exception e) {
                log.warn("Failed to persist idempotency record — transfer already completed", e);
            }
        }

        return ResponseEntity.ok(result);
    }

    @PatchMapping("/{id}/freeze")
    public AccountResponse freeze(@PathVariable UUID id) {
        return accountService.freeze(id);
    }

    @PatchMapping("/{id}/unfreeze")
    public AccountResponse unfreeze(@PathVariable UUID id) {
        return accountService.unfreeze(id);
    }

    @PatchMapping("/{id}/close")
    public AccountResponse close(@PathVariable UUID id) {
        return accountService.close(id);
    }
}
