app = "vaultflow-accounts"
primary_region = "iad"

[build]
  dockerfile = "vaultflow-accounts/Dockerfile"

[env]
  SERVICES_TRANSACTIONS_URL = "http://vaultflow-transactions.internal:8082"
  MANAGEMENT_TRACING_SAMPLING_PROBABILITY = "0.0"
  SPRING_JPA_SHOWSQL = "false"

[http_service]
  internal_port = 8081
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0

[[http_service.checks]]
  grace_period = "60s"
  interval = "30s"
  method = "GET"
  path = "/actuator/health"
  timeout = "10s"

[[vm]]
  memory = "256mb"
  cpu_kind = "shared"
  cpus = 1
