server:
  port: 8081

spring:
  application:
    name: vaultflow-accounts
  datasource:
    url: jdbc:postgresql://localhost:5441/accounts_db
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

services:
  transactions:
    url: http://localhost:8082

management:
  endpoints:
    web:
      exposure:
        include: health,info
